# title of website
title: å¼ å°é±¼

# description of website
description: å¼ å°é±¼çš„æ”¶è—å¤¹

# favicon of website
favicon: "https://github.com/zyyjade.png?size=40"

# your website url
url: https://zyyjade.github.io

# footer message
footer: Â© 2022-2022 @zyyjade

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # å¯é€‰çš„æœç´¢å¼•æ“
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: å¹³é¢è®¾è®¡
      sites:
        - name: 90è®¾è®¡ğŸ’°
          description: åˆ›æ„æ¥æº
          url: https://90sheji.com/
        - name: PSå®¶å›­ğŸ‘
          description: åˆ›æ„æ¥æº
          url: https://www.psjia.com/
        - name: èŠ±ç“£
          description: åˆ›æ„æ¥æº
          url: http://huaban.com/
        - name: ä¼˜è®¾ğŸ’°
          description: åˆ›æ„æ¥æº
          url: http://www.uisdc.com/
        - name: ç«™é…·ğŸ’°
          description: åˆ›æ„æ¥æº
          url: http://www.zcool.com.cn/
        - name: 365PSD
          description: çŸ¢é‡ç´ æ
          url: https://365psd.com/
        - name: CleanPNG
          description: çŸ¢é‡ç´ æ
          url: https://www.cleanpng.com/
        - name: unDraw
          description: çŸ¢é‡ç´ æ
          url: https://undraw.co/illustrations
        - name: Vectorhq
          description: çŸ¢é‡ç´ æ
          url: https://cn.vectorhq.com/
        - name: ç«æŸ´äºº
          description: çŸ¢é‡ç´ æ
          url: https://pictogram2.com/?paged=2&lang=en
        - name: IconFinder
          description: çŸ¢é‡å›¾æ ‡
          url: https://www.iconfinder.com/
        - name: IconFont
          description: çŸ¢é‡å›¾æ ‡
          url: https://www.iconfont.cn/home/index?spm=a313x.7781069.1998910419.2
        - name: å›¾é±¼
          description: èƒŒæ™¯ç´ æ
          url: https://www.hituyu.com/
        - name: 100Font
          description: å…è´¹å­—ä½“
          url: https://www.100font.com/
        - name: DaFont
          description: å…è´¹å­—ä½“
          url: https://www.dafont.com/
        - name: Font2u
          description: å…è´¹å­—ä½“
          url: https://zh.fonts2u.com/
         - name: çŒ«å•ƒç½‘
          description: å…è´¹å­—ä½“
          url: https://www.maoken.com/
        - name: Gradient
          description: æ¸å˜è‰²å½©
          url: https://gradient.shapefactory.co/
        - name: uiGradients
          description: æ¸å˜è‰²å½©
          url: https://uigradients.com/#SunontheHorizon
        - name: ä¸­å›½è‰²
          description: è‰²å½©é…è‰²
          url: http://zhongguose.com/
        - name: åœ¨çº¿é…è‰²
          description: è‰²å½©é…è‰²
          url: https://www.shejidaren.com/examples/tools/color-scheme/
        - name: CGèµ„æºğŸ‘
          description: éŸ³é¢‘ç´ æ
          url: https://www.cgown.com/
        - name: Ignitemotion
          description: éŸ³é¢‘ç´ æ
          url: https://www.ignitemotion.com/
        - name: NewCGğŸ‘
          description: éŸ³é¢‘ç´ æ
          url: https://www.newcger.com/aemoban/
        - name: Pixabay
          description: éŸ³é¢‘ç´ æ
          url: https://pixabay.com/zh/videos/search/?order=ec
        - name: çˆ±ç»™ç½‘ğŸ‘
          description: éŸ³é¢‘ç´ æ
          url: https://www.aigei.com/
        - name: æ¡å±ç¬‘çš„å°ç«™
          description: éŸ³é¢‘ç´ æ
          url: https://jpsmile.com/
        - name: æ·˜å£°ç½‘ğŸ‘
          description: éŸ³é¢‘ç´ æ
          url: https://www.tosound.com/
        - name: Collect UI
          description: Daily inspiration collected from daily ui archive and beyond.
          url: http://collectui.com/
        - name: UI uigreat
          description: APPç•Œé¢æˆªå›¾å‚è€ƒ
          url: http://ui.uigreat.com/
        - name: Android Niceties
          description: A collection of screenshots encompassing some of the most beautiful looking Android apps.
          url: http://androidniceties.tumblr.com/
    - name: ç½‘é¡µçµæ„Ÿ
      sites:
        - name: Awwwards
          description: Awwwards are the Website Awards that recognize and promote the talent and effort of the best developers, designers and web agencies in the world.
          url: https://www.awwwards.com/
